version: 1.0.{build}  

# Defines the machine that is used to run build/test/deploy/...
os: Visual Studio 2015

# Called after cloning the repository.
install:  
  # Add the v3 NuGet feed and myget.org (for moq.netcore package).
  - nuget sources add -Name api.nuget.org -Source https://api.nuget.org/v3/index.json
  - nuget sources add -Name myget.org -Source https://www.myget.org/F/aspnet-contrib/api/v3/index.json
  # Install dnvm.
  - ps: "&{$Branch='dev';iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
  # Install coreclr (no need for startup improvement here)
  - dnvm upgrade -r coreclr -NoNative

# Called before building.
before_build:  
  - dnu restore
  - cd %APPVEYOR_BUILD_FOLDER%\src\Localization.JsonLocalizer

# Replace default build.
build: off  
build_script:  
  - dnu build

# Called before running tests.
before_test:  
  - cd %APPVEYOR_BUILD_FOLDER%\test\Localization.JsonLocalizer.Tests

# Replace default test.
test: off  
test_script:  
  - dnx test